services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
  metabase:
    image: metabase/metabase:latest
    container_name: metabase_app
    ports:
      - "3000:3000"
    environment:
      MB_PASSWORD_COMPLEXITY: normal
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      - .metabase:/metabase-data
  minio:
    image: minio/minio:latest
    entrypoint:
      [
        "minio",
        "server",
        "--address",
        "0.0.0.0:9000",
        "--console-address",
        "0.0.0.0:9001",
        "/data",
      ]
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
  prefect_server:
    image: prefecthq/prefect:3-python3.12
    container_name: prefect_server
    volumes:
      - prefect:/root/.prefect
      - prefect-data:/data # Persistent storage
      - .:/app # Mount current directory
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      # If you want to access Prefect Server UI from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL and PREFECT_API_URL to match the external hostname/IP of the host machine. For example:
      #- PREFECT_UI_URL=http://external-ip:4200/api
      #- PREFECT_API_URL=http://external-ip:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
      # Uncomment the following line if you want to use the 'S3 Bucket' storage block instead of the older 'S3' storage
      # - EXTRA_PIP_PACKAGES=prefect-aws
    ports:
      - 4200:4200
    depends_on:
      - database
  worker:
    image: prefecthq/prefect:3-python3.12
    container_name: prefect_worker
    depends_on:
      - prefect_server
    entrypoint:
      [
        "/opt/prefect/entrypoint.sh",
        "prefect",
        "worker",
        "start",
        "-p",
        "default",
      ]
    volumes:
      - ./flows:/root/flows
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
    #       Use PREFECT_API_KEY if connecting the worker to Prefect Cloud
    #     - PREFECT_API_KEY=YOUR_API_KEY
  cli:
    image: prefecthq/prefect:3-python3.12
    container_name: prefect_cli
    depends_on:
      - prefect_server
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
    environment:
      - PREFECT_API_URL=http://prefect_server:4200/api
    #       Use PREFECT_API_KEY to use the CLI to interact with Prefect Cloud
    #     - PREFECT_API_KEY=YOUR_API_KEY
    profiles: ["cli"]

volumes:
  metabase_data:
  prefect:
  prefect-data:
  db:
  minio:
networks:
  default:
    name: prefect-network
